### ISSUE TITLE
会干扰正常的 run_command 事件

### ISSUE THREAD

**Issue by Cranyozen** [ZhuRuoLing/LetMeClickAndSendForServer#1]
例如以下 tellraw 命令：
`/tellraw @p [{"text":"你好","clickEvent":{"action":"run_command","value":"/say Hello!"}}]`
期待效果为点击 `你好` 字样后会调用 `/say Hello!` 命令 但却直接输出了文本 `/say Hello!`

此处 `/say Hello!` 命令仅为演示 但其他命令均是如此

**Comment by ZhuRuoLing** [comment]
已经解决（

**Comment by ZhuRuoLing** [comment]
请下载最新的action ci的构建结果
