### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by Adogs1** [ZhuRuoLing/LetMeClickAndSendForServer#3]
它能替代https://modrinth.com/mod/letmeclickandsend吗？如果能，请添加对1.20.2版本支持

**Comment by ZhuRuoLing** [comment]
在客户端与服务端均为1.19.1以上的版本时本mod可以替代(letmeclickandsend)[https://modrinth.com/mod/letmeclickandsend]
我已经确认本mod在1.20.2可以正常运行
在modrinth上传的release已经写明本mod兼容[1.19.1, 1.20.4]的Minecraft
<img width="264" alt="image" src="https://github.com/ZhuRuoLing/LetMeClickAndSendForServer/assets/98583550/d5bfd2b9-4993-4c66-bc51-b078be4dbfbe">
