### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Adogs1** [ZhuRuoLing/LetMeClickAndSendForServer#4]
请问我应该如何下载该jar文件？
是否能更新1.21，我打算在1.21服务器上使用它

**Comment by ZhuRuoLing** [comment]
[modrinth下载地址](https://modrinth.com/mod/lmcasforserver/version/1.0.1)
1.21版本将在稍后推出

**Comment by Adogs1** [comment]
> [modrinth下载地址](https://modrinth.com/mod/lmcasforserver/version/1.0.1) 1.21版本将在稍后推出

谢谢
